'use client'

import { useTheme } from 'next-themes'
import Image from 'next/image'

const SkillsContainer: React.FC = () => {
  const {theme} = useTheme()
    
  return (
    <div className="skillsContainer">
      <Image
        src="/skills/HTML.svg"
        alt="html"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Babel.svg"
        alt="Babel"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Bootstrap.svg"
        alt="Bootstrap"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Postman.svg"
        alt="Postman"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Sass.svg"
        alt="Sass"
        width={50}
        height={50}
      />
      <Image
        src="/skills/TypeScript.svg"
        alt="TypeScript"
        width={50}
        height={50}
      />
      <Image
        src="/skills/CSS.svg"
        alt="CSS"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Discord.svg"
        alt="Discord"
        width={50}
        height={50}
      />
      <Image
        src="/skills/Git.svg"
        alt="Git"
        width={50}
        height={50}
      />
      <Image
        src="/skills/JavaScript.svg"
        alt="JavaScript"
        width={50}
        height={50}
      />
      {theme === 'light' ? (
        <>
          <Image
            src="/skills/AndroidStudio-Light.svg"
            alt="AndroidStudio"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Github-Light.svg"
            alt="Github"
            width={50}
            height={50}
          />
          <Image
            src="/skills/GitLab-Light.svg"
            alt="GitLab"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Gradle-Light.svg"
            alt="Gradle"
            width={50}
            height={50}
          />
          <Image
            src="/skills/CodePen-Light.svg"
            alt="CodePen"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Figma-Light.svg"
            alt="Figma"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Firebase-Light.svg"
            alt="Firebase"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Linux-Light.svg"
            alt="Linux"
            width={50}
            height={50}
          />
          <Image
            src="/skills/NeoVim-Light.svg"
            alt="NeoVim"
            width={50}
            height={50}
          />
          <Image
            src="/skills/VIM-Light.svg"
            alt="VIM"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Vite-Light.svg"
            alt="Vite"
            width={50}
            height={50}
          />
          <Image
            src="/skills/VSCode-Light.svg"
            alt="VSCode"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Webpack-Light.svg"
            alt="Webpack"
            width={50}
            height={50}
          />
          <Image
            src="/skills/NextJS-Light.svg"
            alt="NextJS"
            width={50}
            height={50}
          />
          <Image
            src="/skills/React-Light.svg"
            alt="Linux"
            width={50}
            height={50}
          />
        </>
      ) : (
        <>
          <Image
            src="/skills/AndroidStudio-Dark.svg"
            alt="AndroidStudio"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Github-Dark.svg"
            alt="Github"
            width={50}
            height={50}
          />
          <Image
            src="/skills/GitLab-Dark.svg"
            alt="GitLab"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Gradle-Dark.svg"
            alt="Gradle"
            width={50}
            height={50}
          />
          <Image
            src="/skills/CodePen-Dark.svg"
            alt="CodePen"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Figma-Dark.svg"
            alt="Figma"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Firebase-Dark.svg"
            alt="Firebase"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Linux-Dark.svg"
            alt="Linux"
            width={50}
            height={50}
          />
          <Image
            src="/skills/NeoVim-Dark.svg"
            alt="NeoVim"
            width={50}
            height={50}
          />
          <Image
            src="/skills/VIM-Dark.svg"
            alt="VIM"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Vite-Dark.svg"
            alt="Vite"
            width={50}
            height={50}
          />
          <Image
            src="/skills/VSCode-Dark.svg"
            alt="VSCode"
            width={50}
            height={50}
          />
          <Image
            src="/skills/Webpack-Dark.svg"
            alt="Webpack"
            width={50}
            height={50}
          />
          <Image
            src="/skills/NextJS-Dark.svg"
            alt="NextJS"
            width={50}
            height={50}
          />
          <Image
            src="/skills/React-Dark.svg"
            alt="Linux"
            width={50}
            height={50}
          />
        </>
      )
      }
    </div>
  )
}

export default SkillsContainer

